### ISSUE TITLE
Cargo issues errors with the local mirror

### ISSUE THREAD

**Issue by domr2695** [panamax-rs/panamax#10]
Platform: x86_64-Linux-gtk2
OS version: Debian bullseye/sid
Widgetset library: GTK 2.24.32

- Rust 1.48.0 (7eac88abb 2020-11-16)
- nginx 1.18.0-6
- git 2.29.2-1
- panamax 0.2.0

/etc/nginx/sites-available/default :

server {
	listen 80 default_server;
	listen [::]:80 default_server;
        root /mnt/repo/debian/rust/my-mirror;
        server_name localhost; 
	location / {
		autoindex on;
	}
	location ~ /crates.io-index(/.*) {
	# Replace this path with the path to crates.io-index in your mirror directory.
	# fastcgi_param GIT_PROJECT_ROOT    /path/to/my-mirror/crates.io-index;
	fastcgi_param GIT_PROJECT_ROOT    /mnt/repo/debian/rust/my-mirror/crates.io-index;
	include       fastcgi_params;
	fastcgi_pass  unix:/var/run/fcgiwrap.socket;
	fastcgi_param SCRIPT_FILENAME     /usr/lib/git-core/git-http-backend;
	fastcgi_param GIT_HTTP_EXPORT_ALL "";
	fastcgi_param PATH_INFO           $1;
}

/home/u1/.cargo/config :

[source.my-mirror]
registry = "http://localhost/crates.io-index"
[source.crates-io]
replace-with = "my-mirror"

/home/u1/.bashrc :

PATH="$HOME/.cargo/bin:$PATH"
export RUSTUP_DIST_SERVER=http://localhost
export RUSTUP_UPDATE_ROOT=http://localhost/rustup

/mnt/repo/debian/rust/my-mirror/mirror.toml :
	base_url = "http://localhost/crates"

panamax init my-mirror
panamax sync my-mirror
systemctl start nginx

cargo install ripgrep :

    Updating `http://localhost/crates.io-index` index
warning: spurious network error (2 tries remaining): unexpected http status code: 502; class=Http (34)
warning: spurious network error (1 tries remaining): unexpected http status code: 502; class=Http (34)
error: failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `http://localhost/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  unexpected http status code: 502; class=Http (34)

**Comment by k3d3** [comment]
So in this case, it's possible you don't have fcgiwrap installed, and if it is installed, it might not be started and running. This appears to be an issue with how nginx itself is set up though, rather than Panamax itself.

One other option is to use git daemon, which will bypass nginx entirely and simply run a separate git server: https://git-scm.com/book/en/v2/Git-on-the-Server-Git-Daemon

**Comment by k3d3** [comment]
I'm going to close this ticket. If you're still having this issue, feel free to reopen it.
