### ISSUE TITLE
[Enquiry] How big the full mirror is?

### ISSUE THREAD

**Issue by windoze** [panamax-rs/panamax#121]
I want to set up a mirror, but I wonder how much disk space a full mirror needs.
I would appreciate any feedback.

Thanks.

**Comment by rust1248** [comment]
200GB

**Comment by windoze** [comment]
Thanks!
It doesn't sound like a crazy number so I'm going to give a shot.

**Comment by windoze** [comment]
Just confirmed that a full mirror takes 186GB disk storage, not as much as I expected.
Thanks folk, I'm closing this.
