### ISSUE TITLE
[Question] Use S3/minio to host /mirror?

### ISSUE THREAD

**Issue by xulai1001** [panamax-rs/panamax#131]
According to the Readme file, panamax will sync all the crates to a local directory /mirror.
Is it possible to put the mirror onto some local object storage platforms, such as s3 or minio? ( or Gitlab package registry )

**Comment by k3d3** [comment]
As long as you have the ability to mount that S3 bucket as a filesystem, via something like `s3 mountpoint`, it should work. I haven't used S3 in that way before so YMMV.

**Comment by xulai1001** [comment]
Thanks for your timely reply! I can try it out then.

**Comment by xulai1001** [comment]
> As long as you have the ability to mount that S3 bucket as a filesystem, via something like `s3 mountpoint`, it should work. I haven't used S3 in that way before so YMMV.

Unfortunately, I could only sync from a crates mirror site which uses the old directory format, which is unsupported by "newer" versions of panamax. So I just used the original crates.io-index repo and mirrored ".crate" files to enable read-only "cargo fetch" without any external tools.
I may configure a separate private registry for uploading later.
