### ISSUE TITLE
Request: release a new version containing the fix for filtering unix platforms

### ISSUE THREAD

**Issue by felixwrt** [panamax-rs/panamax#132]
I've been trying out panamax by installing it using `cargo install`:

```
cargo install --locked panamax
```

I wanted to create a mirror that only mirrors a single unix platform, but it always downloaded all of them. It took me a while to figure out that this issue had been fixed on main over a year ago (see #96), but the latest version on crates.io still contained the issue.

Can you please release a new version of panamax containing the fix? 

Thanks in advance!

**Comment by k3d3** [comment]
I've published v1.0.14 to crates.io - hopefully this fixes your issue.

Thanks!
