### ISSUE TITLE
rust-src-* files missing on fresh initialization

### ISSUE THREAD

**Issue by k3d3** [panamax-rs/panamax#27]
dear keith

thanks a lot for the quick fix! i did a full re-sync and most things work as expected again!

what does not work is a fresh rust installation. i can download `rust-init` but when i run it `http://pamanax.internal/dist/2021-05-10/rust-src-1.52.1.tar.xz` is not found. the directory `http://pamanax.internal/dist/2021-05-10/` does exist and is populated - but no `rust-src-*` files are in there.

_Originally posted by @panzerballett in https://github.com/panamax-rs/panamax/issues/24#issuecomment-847716190_

**Comment by panzerballett** [comment]
thanks for opening the issue.

i pulled the new version from github (`commit: e0d20b2c5a`),  built it and ran a `sync` right now. a  new directory `dist/2021-05-31/` appeared with many `*.tar.gz` and `*.tar.xz` files in them but no `*-src-*` files are in there.

**Comment by k3d3** [comment]
Looks like this PR https://github.com/panamax-rs/panamax/pull/16 might be the cause. It's filtering out only accepted triples (e.g. unknown-linux-gnu) and doing so by running the filter against the filename.

A workaround would be to remove the `platforms_unix` and `platforms_windows` sections from `mirror.toml` in their entirety, but I will make a fix for this.

**Comment by panzerballett** [comment]
i updated panamax and ran `sync`. worked perfectly!

thanks a lot for the fix!

**Comment by k3d3** [comment]
Awesome, glad to hear!
