### ISSUE TITLE
cargo looks for wrong URL

### ISSUE THREAD

**Issue by panzerballett** [panamax-rs/panamax#39]
hello, me again...

i think the following problem started when the crates.io mirror changed its format (but i am not sure about that).

running `cargo update` on an internal machine works fine - the crates info seems to be updated. but when i try to run `cargo build` (or something similar) this happens:

```
error: failed to download from `http://panamax.internal/crates/bitflags/bitflags-1.3.2.crate`

Caused by:
  failed to get 200 response from `http://panamax.internal/crates/bitflags/bitflags-1.3.2.crate`, got 404
```

what does exist on my local mirror is:
```
http://panamax.internal/crates/bi/tf/bitflags/1.3.2/bitflags-1.3.2.crate
```

on the external machine i built `pamamax` manually, upgraded everything to the latest version and ran `panamax sync`:
```
$ git pull origin master 
$ cargo build --release
$ ./target/release/panamax sync mirror/
```

versions:
```
panamax 1.0.0
cargo 1.54
```

any advice?

**Comment by k3d3** [comment]
The storage format changed recently, but that's still strange it's not getting the right URL.

Are you using `panamax serve` on the serving side, or nginx?

If you're using nginx, you'll likely need some rewrite config settings:

```
	# Rewrite the download URLs to match the proper crates location.
	rewrite "^/crates/([^/])/([^/]+)$"                     "/crates/1/$1/$2"         last;
	rewrite "^/crates/([^/]{2})/([^/]+)$"                  "/crates/2/$1/$2"         last;
	rewrite "^/crates/([^/])([^/]{2})/([^/]+)$"            "/crates/3/$1/$1$2/$3"    last;
	rewrite "^/crates/([^/]{2})([^/]{2})([^/]*)/([^/]+)$"  "/crates/$1/$2/$1$2$3/$4" last;
```

from https://github.com/panamax-rs/panamax/blob/master/nginx.sample.conf

If you already have those in your nginx config, or you're using `panamax serve` and it's still not working, that's indeed strange.

**Comment by panzerballett** [comment]
thanks a lot for your *QUICK* reply!

i use `nginx` directly - without `panamax serve`.

the rewrite rules helped although i had to tweak them a little in order to take the version number of the crates into account:

```
        rewrite "^/crates/([^/])/([^/]+)-([\d\.]*).crate$"                     "/crates/1/$1/$3/$2-$3.crate"          last;
        rewrite "^/crates/([^/]{2})/([^/]+)-([\d\.]*).crate$"                  "/crates/2/$1/$3/$2-$3.crate"          last;
        rewrite "^/crates/([^/])([^/]{2})/([^/]+)-([\d\.]*).crate$"            "/crates/3/$3/$4/$3-$4.crate"          last;
        rewrite "^/crates/([^/]{2})([^/]{2})([^/]*)/([^/]+)-([\d\.]*).crate$"  "/crates/$1/$2/$1$2$3/$5/$4-$5.crate"  last;
```

i did not run exhaustive tests but it did work for a few simple cases (obviously i'm no regex wizard...).

would it be beneficial to run `panamax serve`?

thanks again and best regards!

**Comment by k3d3** [comment]
Apologies for the late reply.

Yeah, I think `panamax serve` is the best option for this. If that command doesn't work for you, let me know.

Also, good to know with regards to the rewrite rules! I'll quickly review those. Thanks!

**Comment by nicoxxl** [comment]
Also, this [PR](https://github.com/panamax-rs/panamax/pull/47), I have removed the need for URL rewriting.

**Comment by JustAnotherCodemonkey** [comment]
@k3d3 
> If you already have those in your nginx config, or you're using `panamax serve` and it's still not working, that's indeed strange.

I'm using `panamax serve` on macos and am getting a similar issue. Following the README tutorial with `panamax serve` and using installing ripgrep as a dummy and get the following output from cargo:
```
cargo install --config "source.crates-io.replace-with=\"panamax\"" ripgrep
    Updating `panamax` index
warning: spurious network error (3 tries remaining): [6] Couldn't resolve host name (Could not resolve host: panamax.internal)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: panamax.internal)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: panamax.internal)
error: failed to download from `http://panamax.internal/crates/ri/pg/ripgrep/13.0.0/ripgrep-13.0.0.crate`
```

**Comment by JustAnotherCodemonkey** [comment]
Sorry to keep updating but now I've meddled in mirror.toml and now can't get the same error. Now I get
```
cargo install --config "source.crates-io.replace-with=\"panamax\"" ripgrep
    Updating `panamax` index
warning: spurious network error (3 tries remaining): unexpected http status code: 404; class=Http (34)
warning: spurious network error (2 tries remaining): unexpected http status code: 404; class=Http (34)
warning: spurious network error (1 tries remaining): unexpected http status code: 404; class=Http (34)
error: failed to update replaced source registry `crates-io`

Caused by:
  failed to fetch `http://localhost:8080/git/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  unexpected http status code: 404; class=Http (34)
```
With the server outputting
```
Not a git repository: 'crates-mirror/crates.io-index'Not a git repository: 'crates-mirror/crates.io-index'Not a git repository: 'crates-mirror/crates.io-index'Not a git repository: 'crates-mirror/crates.io-index'
```

**Comment by JustAnotherCodemonkey** [comment]
Ok now I got it back to the problem with panamax.internal somehow.

**Comment by JustAnotherCodemonkey** [comment]
Ugh I feel very slightly stupid. I for some reason didn't figure out that the base_url would have to be actually what cargo would connect to. Should have read the docs more thoroughly. Sorry.
