### ISSUE TITLE
Bug in sync rustup-init files for windows platforms

### ISSUE THREAD

**Issue by TalRoni** [panamax-rs/panamax#48]
rustup-init files in windows platforms need `.exe` extension in the download url
The `sync_rustup_init` always call to `sync_one_init` with `is_exe=false` as parameter

**Comment by TalRoni** [comment]
#49

**Comment by TalRoni** [comment]
Hi @k3d3 
Do you have any comments about this patch? want to make the changes?
Thanks

**Comment by LukeMauldin** [comment]
This is impacting me because I cannot replace Romt with Panamax because Rustup-init files for windows are not being downloaded.

**Comment by k3d3** [comment]
I've merged PR #49, which should fix this bug. Feel free to reopen this issue if it still persists.
