### ISSUE TITLE
Docker container - panamax serve broken

### ISSUE THREAD

**Issue by g-radam** [panamax-rs/panamax#51]
Serving panamax within a container, and attempting to fetch packages via cargo fails with response 500. I debugged and identified the container does not have git installed which is invoked in the Rust code. Its possible the Debian base image had git installed in a previous version, but has since been removed? Regardless, manually adding git resolves the issue.

Dockerfile patch:
```
---
RUN apt install -y libssl1.1 ca-certificates
---
+++
RUN apt install -y libssl1.1 ca-certificates git
+++
```

**Comment by k3d3** [comment]
Oh no! Good catch, thank you! I'll try to get this fixed over the weekend.

**Comment by g-radam** [comment]
Champion! Thanks k3d3.
