### ISSUE TITLE
Platforms for rustup failing to download, mipsel-unknown-linux-musl

### ISSUE THREAD

**Issue by aterribleloss** [panamax-rs/panamax#60]
Despite not specifying `platforms_unix` or `platforms_windows`, which according to the documentation it should download all the rustup versions.
rustup for the architecture `mipsel-unknown-linux-musl` is failing to download any of the rustup distribution files.

**Comment by k3d3** [comment]
I've made changes to Panamax v1.0.5 in order to address this, allowing platforms not listed in the hardcoded default list. Let me know if it works for you now.
