### ISSUE TITLE
Missing crates not downloaded when syncing mirror

### ISSUE THREAD

**Issue by ricked-twice** [panamax-rs/panamax#64]
Hi there :wave: !
First of all, well done for your work on `panamax` !

So, the issue here has already been highlighted in others issues (same author):

- [issue#55](https://github.com/panamax-rs/panamax/issues/55): the issue's author seemed to have an incoherent mirror. To solve it, he had to delete his actual mirror and sync a new mirror from scratch. I already met this issue, and had to go through the same process. But is is a costly solution (in my opinion), and the cost will only grow as `crates.io` will reference more and more crates.
- [issue#8](https://github.com/panamax-rs/panamax/issues/8)): author used the same fix here.

I opened a pull request in January to add a feature to `panamax` allowing users to check for missing crates in the synced mirror [PR#57](https://github.com/panamax-rs/panamax/pull/57).
The check is not fetching the `crates.io-index`, but just looking at the the local index state.

I closed it as I had no feedback from you. But I decided to still open an issue about it.

I couldn't find a way to trigger the problem using `panamax`, but I decided to manually delete some crates from my local mirror.
Here are the steps I did (from my [`panamax`'s fork](https://github.com/ricked-twice/panamax)):

1. Removed `/path/to/my/mirror/crates/fa/st/fastrand/` and `/path/to/my/mirror/crates/ri/ng/ring/0.16.20/`
2. Ran `cargo run -- verify /path/to/my/mirror`. The manually deleted crate are spotted by the check.
3. Ran `cargo run -- sync /path/to/my/mirror`. Everything went find according to the execution's output.
4. Ran `cargo run -- verify /path/to/my/mirror`. The manually deleted crate are still spotted by the check.
5. Ran `ls /path/to/my//mirror/crates/fa/st/fastrand /path/to/my//mirror/crates/ri/ng/ring/0.16.20` just to be sure. And get `No such file or directory` error for both directory.

There are two things highlighted by this issue:

1. If, for some reason, some crates are deleted for the mirror, `panamax` is not able to download them again because of the fact that the reference to download crates is a diff between the local index (`master` branch) and the distant one (`origin/master` branch). This makes sense that the missing crates are not downloaded.
2. That behavior does not explain why the mirror can sometimes be in an inconsistent state without any crates removal.

By exchanging about it around me, I've been put on the track that it could come from the fact that our local commit have been squashed on origin which result of local commit id to be absent from the tree. But I've looked into `panamax`'s code and you seem to handle this case. So, I can't figure a reason of this behavior.

Anyway, I hope this issue will lead to some discussion, and if you need help, I'd be glad to re-open a PR.

Cheers :smile:

**Comment by JamesMConroy** [comment]
I'm facing the same issue, specifically with `cargo-make`. There was a new release for that project, but panamax is unable to grab it.

**Comment by ricked-twice** [comment]
@k3d3 Sorry, just saw your answer, didn't get any notification weirdly !
Do you want me to submit a PR again or should I try to add another feature to download missing crates ?

**Comment by k3d3** [comment]
No worries at all! Yes, please do go ahead and reopen the PR, and I'll make a review on it.

Thank you!

**Comment by JamesMConroy** [comment]
Can you just reopen #57 instead of creating a whole new pull request?

**Comment by k3d3** [comment]
Sure thing!

**Comment by JamesMConroy** [comment]
Looks like #57 is merged. Does everyone think that resolves this issue?

**Comment by k3d3** [comment]
Yep, that should give the ability for people to make sure any missed crates get downloaded, so hopefully that solves the issue for most people. I'll close the issue - feel free to bump/reopen this issue if it still persists.

**Comment by ricked-twice** [comment]
Just to be clear I did not added the feature yet, I was waiting for any comment about [my last comment](https://github.com/panamax-rs/panamax/issues/64#issuecomment-1117577699) which was a suggestion and a proposition to do it if it was interesting you.

Anyway, I'll try to do it in next few days.
