### ISSUE TITLE
Container Image Fails to run

### ISSUE THREAD

**Issue by JamesMConroy** [panamax-rs/panamax#65]
When trying to run the latest container image (tag 1.0.6) I get the following symbol issue.

```
/usr/local/bin/panamax: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/panamax
```

This occurs with the init, sync, and serve commands.

**Comment by JamesMConroy** [comment]
I don't know why but if I build the container myself the error disappears. Maybe it just needs to be rebuilt (or podman does something different from docker)

**Comment by k3d3** [comment]
Interesting - I don't understand why that would be happening, considering I'm using the official rust image as a base. The only thing I could think of is I'm running the docker builds on an Arch host, which probably has a newer GLIBC version. But that shouldn't affect what happens *inside* docker, since that image should have its own GLIBC version.

I'll take a further look into it.

**Comment by k3d3** [comment]
Oh, I figured it out. I have a multistage dockerfile which builds with `rust:latest` and then copies it to `debian:latest` for hosting. For now I'll just switch the two to rust, which kinda defeats the purpose of multistage, but that should at least make it work.

**Comment by k3d3** [comment]
Now I'm realizing that the `rust` image is based on the `debian` image, and my issue was that I had pulled the latest `rust` but *not* the latest `debian`. Doing that has fixed the issues, so I'll just re-push the images.

(at some point I'll have to throw this into Github Actions)

**Comment by JamesMConroy** [comment]
Yay. I've been meaning to learn GH actions, so I'll take a look at getting a build and test going.

**Comment by JamesMConroy** [comment]
Created #66 to build and run the image on every push and MR. It should also push it to docker hub.

**Comment by JamesMConroy** [comment]
With #66 merged this issue should be caught earlier, and this issue can be closed.
