### ISSUE TITLE
Support PGP signature validation on rustup files

### ISSUE THREAD

**Issue by k3d3** [panamax-rs/panamax#7]
Rustup itself currently doesn't validate PGP signatures, however the signatures appear to exist on the server. 

Possibly use https://github.com/rust-lang/rustup/issues/2028 as a starting point to figure out how to validate everything?

**Comment by DrChat** [comment]
To add to this issue - it doesn't appear that panamax pulls in `.asc` files for rustup channels.

**Comment by k3d3** [comment]
Noted! That'll be a good first step, at least.
