### ISSUE TITLE
Add a way to restart a sync

### ISSUE THREAD

**Issue by ModProg** [panamax-rs/panamax#72]
My initial sync took hours and then died, afterwards I needed to sync all files again.

Maybe it would be possible to restart from the already downloaded files so you don't need to redownload all crates again?

**Comment by k3d3** [comment]
Oh weird, it should support the use-case of resuming after a dead sync.

**Comment by k3d3** [comment]
I'm going to close this issue. Let me know if you're still running into this problem.
