### ISSUE TITLE
Not syncing some dists

### ISSUE THREAD

**Issue by JamesMConroy** [panamax-rs/panamax#74]
Panamax doesn't seem to sync the files for tier 3 targets like 

- `mips-unknown-linux-musl`
- `mipsel-unknown-linux-musl`
- `armv7-unknown-linux-musleabihf`

It would be great to also grab these targets with a sync.

**Comment by JamesMConroy** [comment]
If I'm reading the code right it should just be a matter of adding the platforms here

https://github.com/panamax-rs/panamax/blob/master/src/rustup.rs#L23

**Comment by k3d3** [comment]
You would be correct! Having this list in general is a bad idea because it needs to be constantly updated. I'll need to fix that eventually.

For now, would you be able to make a PR containing these added targets?

**Comment by JamesMConroy** [comment]
#76 created.

I wish I knew rust enough to replace the list with an api call or something.

Oh well something to think about
