### ISSUE TITLE
Update version to 1.0.7 and create new docker image for new vendor feature?

### ISSUE THREAD

**Issue by roarbr** [panamax-rs/panamax#81]
Hi,

PR #71 added an option to use cargo vendor to download only selected packages. 
The Panamax version number is not updated after this feature and the latest docker hub image (version 1.0.6) does not have this feature.

Could you create a new version and build a new docker image with this feature included?

**Comment by wcampbell0x2a** [comment]
It would also be nice to tag this repo when new versions are pushed to crates.io.

**Comment by k3d3** [comment]
This should be pushed to crates.io and docker now.
