### ISSUE TITLE
After configuring panamax and cargo, the later keeps attempting to connect to panamax.internal

### ISSUE THREAD

**Issue by ivan-jli** [panamax-rs/panamax#84]
Am I doing something incorrectly? I greped for ‘panamax\.internal’ under ~/.cargo and panamax/mirror, no results. Why cargo still searches for this name?

**Comment by ivan-jli** [comment]
$ cargo build 
warning: spurious network error (1 tries remaining): (6] Couldn't resolve host name (Could not resolve host: panamax.internal)

**Comment by wcampbell0x2a** [comment]
What is your `base_url` set to in the `mirror.toml` file?

**Comment by k3d3** [comment]
Make sure your `base_url` in `mirror.toml` is set to something other than `panamax.internal`, and then run `panamax rewrite .` to update the index with the new `base_url`.
