### ISSUE TITLE
Downloading crates.io-index repository failed: GitError(Error { code: -1, klass: 16, message: "the server did not provide a certificate" })

### ISSUE THREAD

**Issue by mattfbacon** [panamax-rs/panamax#85]
I get this error when fetching the crates.io index. I didn't change the default configuration at all except disabling Rustup sync (so I could get to this error faster).

**Comment by k3d3** [comment]
Can you try again with the latest version (1.0.7)? I've updated the dependencies and that seems to have fixed it for me.

**Comment by mattfbacon** [comment]
Seems to work, thanks
